[theme]
base = "dark"
primaryColor = "#e11d48"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"

[server]
maxUploadSize = 5
enableXsrfProtection = true

[browser]
gatherUsageStats = false
